---
abstract: 'Perl wrapper to librados.'
author:
  - 'Alex <alex@openimp.com>'
dynamic_config: 1
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v2.0.html
  version: '2.0'
name: Ceph-Rados
no_index:
  directory:
    - t
    - inc
prereqs:
  configure:
    requires:
      Devel::CheckLib: '0'
      ExtUtils::MakeMaker: '0'
      File::Which: '0'
      C::Scan::Constants: '0'
  test:
    requires:
      Test::More: '0'
      Test::Exception: '0'
      Data::Dump: '0'
version: '0.13'
